# This is a workflow to get testing coverage.

name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    
    - uses: pip install coverage
    - name: Run coverage 
      run: coverage run  --source=. -m pytest
 
    - name: Get coverage report 
      run: coverage report 

